default_install_hook_types: [pre-commit, commit-msg]

repos:
  - repo: "https://github.com/commitizen-tools/commitizen"
    rev: "v2.18.0"
    hooks:
      - id: commitizen
        stages: [commit-msg]

  - repo: "https://github.com/pre-commit/mirrors-prettier"
    rev: "v2.7.1"
    hooks:
      - id: prettier
        stages: [pre-commit]
        exclude: tests\/test_.+\.

  - repo: https://github.com/charliermarsh/ruff-pre-commit
    rev: "v0.7.0"
    hooks:
      - id: ruff
        stages: [pre-commit]
      - id: ruff-format
        stages: [pre-commit]

  - repo: https://github.com/codespell-project/codespell
    rev: v2.2.4
    hooks:
      - id: codespell
        stages: [pre-commit]
        additional_dependencies:
          - tomli
